CREATE DATABASE boardgame;

CREATE TABLE player(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(60) NOT NULL
);

CREATE TABLE score(
    id SERIAL PRIMARY KEY,
    score INT NOT NULL,
    player_id INT NOT NULL REFERENCES player(id) ON DELETE CASCADE
);